import {
  RTCPeerConnection,
  RTCIceCandidate,
  RTCSessionDescription,
  mediaDevices,
  type MediaStream,
} from "react-native-webrtc";

import { activateCallAudioSession } from "@/services/audioSession";
import type { RTCIceCandidateInit, RTCSessionDescriptionInit } from "@/types/call";

// RTCIceServer as defined inside react-native-webrtc (not re-exported from index)
export interface RTCIceServer {
  urls?: string | string[];
  username?: string;
  credential?: string;
}

// ─── Module state ─────────────────────────────────────────────────────────────

let pc: RTCPeerConnection | null = null;
let localStream: MediaStream | null = null;

// ICE candidates that arrive before setRemoteDescription completes are buffered
// here and flushed immediately after remote description is set.
let iceCandidateBuffer: RTCIceCandidateInit[] = [];
let remoteDescSet = false;

let iceCandidateCb: ((candidate: RTCIceCandidateInit | null) => void) | null = null;
let remoteStreamCb: ((stream: MediaStream) => void) | null = null;

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Create a new RTCPeerConnection with the given ICE servers.
 * Must be called before any other method.
 */
export function initPeerConnection(iceServers: RTCIceServer[]): void {
  if (pc) {
    console.warn("[WEBRTC] initPeerConnection called with existing pc — closing first");
    close();
  }

  pc = new RTCPeerConnection({ iceServers } as any);

  (pc as any).onicecandidate = (event: any) => {
    const candidate = event.candidate;
    if (candidate) {
      iceCandidateCb?.(candidate.toJSON() as RTCIceCandidateInit);
    }
  };

  (pc as any).ontrack = (event: any) => {
    const stream = event.streams?.[0];
    if (stream) remoteStreamCb?.(stream);
  };

  (pc as any).oniceconnectionstatechange = () => {
    console.log("[WEBRTC] ICE state:", (pc as any)?.iceConnectionState);
  };

  console.log("[WEBRTC] peer connection initialized");
}

/**
 * Request microphone access, attach the local audio track to the peer connection,
 * and activate the call audio session (earpiece mode).
 */
export async function attachLocalAudio(): Promise<MediaStream> {
  if (!pc) throw new Error("[WEBRTC] initPeerConnection must be called first");

  const stream = (await mediaDevices.getUserMedia({ audio: true, video: false })) as MediaStream;
  localStream = stream;

  stream.getTracks().forEach((track) => {
    (pc as RTCPeerConnection).addTrack(track as any, stream);
  });

  await activateCallAudioSession();

  console.log("[WEBRTC] local audio attached");
  return stream;
}

/**
 * Create an SDP offer (caller side).
 * Sets local description internally.
 */
export async function createOffer(): Promise<RTCSessionDescriptionInit> {
  if (!pc) throw new Error("[WEBRTC] no peer connection");
  const offer = await pc.createOffer({} as any);
  await pc.setLocalDescription(offer as any);
  console.log("[WEBRTC] offer created");
  return { type: offer.type, sdp: offer.sdp } as RTCSessionDescriptionInit;
}

/**
 * Create an SDP answer (callee side).
 * Sets remote description from the offer, then creates and sets local description.
 */
export async function createAnswer(
  remoteOffer: RTCSessionDescriptionInit
): Promise<RTCSessionDescriptionInit> {
  if (!pc) throw new Error("[WEBRTC] no peer connection");
  await pc.setRemoteDescription(new RTCSessionDescription(remoteOffer as any));
  remoteDescSet = true;
  await _flushIceBuffer();
  const answer = await pc.createAnswer();
  await pc.setLocalDescription(answer as any);
  console.log("[WEBRTC] answer created");
  return { type: answer.type, sdp: answer.sdp } as RTCSessionDescriptionInit;
}

/**
 * Set the remote answer received from the callee (caller side).
 */
export async function setRemoteAnswer(answer: RTCSessionDescriptionInit): Promise<void> {
  if (!pc) throw new Error("[WEBRTC] no peer connection");
  await pc.setRemoteDescription(new RTCSessionDescription(answer as any));
  remoteDescSet = true;
  await _flushIceBuffer();
  console.log("[WEBRTC] remote answer set");
}

/**
 * Add a remote ICE candidate.
 * Buffered automatically if called before setRemoteDescription completes.
 */
export async function addIceCandidate(candidate: RTCIceCandidateInit): Promise<void> {
  if (!remoteDescSet) {
    iceCandidateBuffer.push(candidate);
    console.log("[WEBRTC] ICE candidate buffered (remote desc not set yet)");
    return;
  }
  if (!pc) return;
  await pc.addIceCandidate(new RTCIceCandidate(candidate as any));
}

/**
 * Register a callback for local ICE candidates generated by the peer connection.
 * Pass these to the peer via the signaling WebSocket.
 */
export function onIceCandidate(
  cb: (candidate: RTCIceCandidateInit | null) => void
): void {
  iceCandidateCb = cb;
}

/**
 * Register a callback for the remote audio stream arriving from the peer.
 */
export function onRemoteStream(cb: (stream: MediaStream) => void): void {
  remoteStreamCb = cb;
}

/**
 * Mute or unmute the local audio track.
 */
export function toggleMute(muted: boolean): void {
  localStream?.getAudioTracks().forEach((track) => {
    (track as any).enabled = !muted;
  });
}

/**
 * Tear down the peer connection and release all resources.
 */
export function close(): void {
  localStream?.getTracks().forEach((t) => (t as any).stop());
  localStream = null;
  pc?.close();
  pc = null;
  iceCandidateBuffer = [];
  remoteDescSet = false;
  console.log("[WEBRTC] peer connection closed");
}

// ─── Private helpers ──────────────────────────────────────────────────────────

async function _flushIceBuffer(): Promise<void> {
  if (!pc || iceCandidateBuffer.length === 0) return;
  console.log("[WEBRTC] flushing", iceCandidateBuffer.length, "buffered ICE candidate(s)");
  for (const candidate of iceCandidateBuffer) {
    await pc.addIceCandidate(new RTCIceCandidate(candidate as any));
  }
  iceCandidateBuffer = [];
}
